app/core/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

urlpatterns = [
    path("", views.index),
    path("emedict/", include("emedict.urls")),
    path("admin/", admin.site.urls),
]

app/emedict/urls.py
from django.urls import path, include
from rest_framework import routers

from . import views

app_name = "emedict"

router = routers.DefaultRouter()
router.register(r"lemma", views.LemmaViewSetSerialized)

urlpatterns = [
    path("", views.index, name="index"),
    path("lemma/", views.LemmaListView.as_view(), name="lemma_home"),
    path("lemma/search", views.LemmaSearchView.as_view(), name="lemma_search"),
    path("lemma/<int:pk>/", views.LemmaIdView.as_view(), name="lemma"),
    path("lemma/<int:pk>.json", views.lemma_json, name="lemma_json"),
    path("lemma/<int:pk>.ttl", views.lemma_ttl, name="lemma_ttl"),
    path("lemma/emesal/", views.LemmaEmesalListView.as_view(), name="lemesal"),
    path("tags/", views.tags, name="tags_home"),
    path("tags/<int:pk>/", views.TagIdView.as_view(), name="tag_id"),
    path("compverbs/", views.CompVerbView.as_view(), name="comp_verbs"),
    path("compverbs/<int:pk>/", views.CompVerbComponentView.as_view(), name="compverbcomp"),
    path("txtsources/<int:pk>/", views.TxtSourceView.as_view(), name="txtsource"),
    path("txtsources/", views.TxtSourceListView.as_view(), name="txtsource_list"),
    path("api/", include(router.urls), name="api")
]

app/emedictsite/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

urlpatterns = [
    path("", views.index),
    path("emedict/", include("emedict.urls")),
    path("admin/", admin.site.urls),
]

app/emedict/models.py
from django.db import models
from django.db.models import Q

import re
import json
from rdflib import Graph, Literal, URIRef, RDF, RDFS, Namespace, BNode

class TxtSource(models.Model):
    abbr = models.CharField(max_length=200, blank=True)
    title = models.CharField(max_length=1000)
    url = models.URLField(max_length=200, blank=True)
    notes = models.TextField(blank=True)

    def __str__(self) -> str:
        return self.title

class Pos(models.Model):
    PTYPES = {
        "COM": "Common",
        "PROP": "Proper nouns"
    }
    abbr = models.CharField(max_length=5)
    term = models.CharField(max_length=50)
    type = models.CharField(max_length=5, choices=PTYPES)
    notes = models.TextField(blank=True)

    def __str__(self) -> str:
        return self.term

class Tag(models.Model):
    TAGTS = {
        "GR": "Grammar",
        "CO": "Content",
        "SO": "Source",
        "WL": "Word list",
        "SH": "Sign Shape"
    }
    term = models.CharField(max_length=200)
    type = models.CharField(choices=TAGTS, max_length=200)
    definition = models.TextField(blank=True)

    def __str__(self) -> str:
        return self.term

class Lemma(models.Model):
    STATUSES = {
        "NR": "not reviewed",
        "R": "reviewed",
        "RD": "reviewed and documented"
    }

    SORTS = {
        "ŋ": "gz",
        "š": "sz",
        "ř": "rz",
        "ḫ": "hz"
    }

    status = models.CharField(choices=STATUSES, default="NR", max_length=5)
    cf = models.CharField(max_length=200)
    pos = models.ForeignKey(Pos, blank=True, null=True, on_delete=models.SET_NULL)
    notes = models.TextField(blank=True)
    tags = models.ManyToManyField(Tag, through="LemmaTag", blank=True)
    components = models.ManyToManyField("self", symmetrical=False, blank=True)
    sortform = models.CharField(max_length=200)

    def base_spelling(self) -> "Spelling":
        if baseform := Form.objects.filter(lemma=self, base=True).first():
            return Spelling.objects.filter(form=baseform).first()
        else:
            firstform = Form.objects.filter(lemma=self).first()
            return Spelling.objects.filter(form=firstform).first()

    def emesal_spelling(self) -> "Spelling":
        emeform = Form.objects.filter(lemma=self, formtype__term="emesal").first()
        return Spelling.objects.filter(form=emeform).first()
    
    def emesal_form(self) -> "Form":
        return Form.objects.filter(lemma=self, formtype__term="emesal").first()

    def make_sortform(self) -> str:
        sortform = self.cf.lower()
        for source, target in self.SORTS.items():
            sortform = re.sub(source, target, sortform)

        return sortform

    def update_sortform(self) -> None:
        self.sortform = self.make_sortform()

    def change_h(self):
        newcf = re.sub("h", "ḫ", self.cf)
        newcf = re.sub("H", "Ḫ", newcf)

        self.cf = newcf

    def merge_lem(self, duplicate: "Lemma"):
        """Merges oids, definitions, forms, and components (if any)
        from ::duplicate:: into self.
        """
        own_components = self.components.count()
        dup_components = duplicate.components.count()
        if (own_components == dup_components) and (own_components > 0):
            dup_cs = set([c for c in duplicate.components.all()])
            own_cs = set([c for c in self.components.all()])
            if not own_cs == dup_cs:
                print("All lemma components must match to merge")
                exit()
            print("All components match")
        elif (own_components > 0 and dup_components == 0) or (own_components == 0 and dup_components > 0):
            print("Cannot merge compound lemma with non-compound lemma")
            exit()
        elif own_components == 0 and dup_components == 0:
            print("No components")

        for oid in duplicate.lemmaoid_set.filter(
            ~Q(oid__in=[e for e in self.lemmaoid_set.all()])
        ):
            newoid = LemmaOid(
                lemma=self,
                oid=oid
            )
            newoid.save()

        for lemdef in duplicate.definitions.all():
            lemdef.lemma=self
            lemdef.save()

        for form in duplicate.forms.all():
            form.lemma=self
            form.save()

        part_ofs = Lemma.objects.filter(components=duplicate)
        for part_of in part_ofs:
            part_of.components.add(self)
            part_of.components.remove(duplicate)
            part_of.save()

        # duplicate.delete()

    def _make_rdf(self, lem_uri) -> Graph:
        ONTOLEX = Namespace("http://www.w3.org/ns/lemon/ontolex#")
        LEXINFO = Namespace("http://www.lexinfo.net/ontology/3.0/lexinfo#")

        g = Graph()
        g.bind("ontolex", ONTOLEX)
        g.bind("lexinfo", LEXINFO)

        lemuri = URIRef(lem_uri)

        if self.components.count() > 0:
            ltype = ONTOLEX.MultiwordExpression
        else:
            ltype = ONTOLEX.Word

        match self.pos.term:
            case "verb":
                g.add((lemuri, LEXINFO.partOfSpeech, LEXINFO.Verb))
            case "noun":
                g.add((lemuri, LEXINFO.partOfSpeech, LEXINFO.Noun))
            case _:
                ...

        g.add((lemuri, RDF.type, ltype))
        g.add((lemuri, RDFS.label, Literal(self.cf)))

        for form in self.forms.all():
            formuri = BNode()
            g.add((lemuri, ONTOLEX.lexicalform, formuri))
            g.add((formuri, RDF.type, ONTOLEX.Form))
            g.add((formuri, RDFS.label, Literal(form.cf)))

        return g

    def make_jsonld(self, lem_uri):
        context = {
            "lexinfo": "http://www.lexinfo.net/ontology/3.0/lexinfo#",
            "ontolex": "http://www.w3.org/ns/lemon/ontolex#",
            "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
            "rdfs": "http://www.w3.org/2000/01/rdf-schema#"
        }
        return json.loads(self._make_rdf(lem_uri).serialize(format="json-ld", context=context))

    def make_ttl(self, lem_uri) -> str:
        return self._make_rdf(lem_uri).serialize(format="ttl")

    def __str__(self) -> str:
        return f"{self.cf} ({self.pk})"

class LemmaOid(models.Model):
    lemma = models.ForeignKey(Lemma, on_delete=models.CASCADE)
    oid = models.CharField(max_length=20, blank=True)

    def __str__(self) -> str:
        return self.oid

class LemmaCitation(models.Model):
    lemma = models.ForeignKey(Lemma, on_delete=models.CASCADE)
    citation = models.CharField(max_length=1000)
    gloss = models.CharField(max_length=1000, blank=True)
    trans = models.CharField(max_length=1000, blank=True)
    lines = models.CharField(max_length=100, blank=True)
    source = models.ForeignKey(TxtSource, on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self) -> str:
        return self.citation

class LemmaDef(models.Model):
    lemma = models.ForeignKey(Lemma, on_delete=models.CASCADE, related_name="definitions")
    definition = models.TextField()

    def __str__(self) -> str:
        return self.definition

class LemmaTag(models.Model):
    lemma = models.ForeignKey(Lemma, on_delete=models.CASCADE)
    tag = models.ForeignKey(Tag, on_delete=models.CASCADE)
    citation = models.TextField(blank=True)
    tagsource = models.ForeignKey(TxtSource, blank=True, null=True, on_delete=models.SET_NULL)

    def __str__(self) -> str:
        return self.lemma.cf + ": " + self.tag.term

class FormType(models.Model):
    term = models.CharField(max_length=200)
    definition = models.TextField(blank=True)

    def __str__(self) -> str:
        return self.term

class Form(models.Model):
    lemma = models.ForeignKey(Lemma, on_delete=models.CASCADE, related_name="forms")
    cf = models.CharField(max_length=200, blank=True)
    formtype = models.ManyToManyField(FormType, blank=True)
    base = models.BooleanField(default=False)

    def __str__(self) -> str:
        return self.cf

# class Sign(models.Model):
#     transcription = models.CharField(max_length=200)
#     cuneiform = models.CharField(max_length=10, blank=True)
#     oid = models.CharField(max_length=10, blank=True)
#     note = models.TextField(blank=True)

#     def __str__(self):
#         return self.transcription

# class SignReading(models.Model):
#     sign = models.ForeignKey(Sign, on_delete=models.CASCADE)
#     reading = models.CharField(max_length=200)
#     note = models.CharField(max_length=200, blank=True)

#     def __str__(self):
#         return self.reading

class Spelling(models.Model):
    form = models.ForeignKey(Form, on_delete=models.CASCADE, related_name="spellings")
    spelling_lat = models.CharField(max_length=200)
    spelling_cun = models.CharField(max_length=200, blank=True)
    # signs = models.ManyToManyField(Sign, blank=True)
    note = models.CharField(max_length=200, blank=True)

    def __str__(self) -> str:
        return self.spelling_lat

app/emedict/forms.py
from django import forms

LETTERS = [
    ("A", "A"), 
    ("B", "B"), 
    ("D", "D"), 
    ("E", "E"), 
    ("G", "G"), 
    ("Ŋ", "Ŋ"), 
    ("H", "H"), 
    ("Ḫ", "Ḫ"), 
    ("I", "I"), 
    ("K", "K"),
    ("L", "L"), 
    ("M", "M"), 
    ("N", "N"), 
    ("P", "P"), 
    ("R", "R"), 
    ("Ř", "Ř"), 
    ("S", "S"), 
    ("Š", "Š"), 
    ("T", "T"), 
    ("U", "U"), 
    ("Z", "Z")]

SEARCH_OPTIONS = [
    ("lemma", "lemma"),
    ("definition", "definition")
]

class LemmaAdvancedSearchForm(forms.Form):
    search_term = forms.CharField(label="Search", max_length=100)
    search_type = forms.CharField(
        label="Search type",
        widget=forms.Select(choices=SEARCH_OPTIONS)
    )

class LemmaInitialLetterForm(forms.Form):
    initial = forms.ChoiceField(
        widget=forms.RadioSelect(
            attrs={"class": "lem_init"}
        ),
        choices=LETTERS,
        required=False
    )

class FacetSideBarForm(forms.Form):
    poss = forms.MultipleChoiceField(
        required=False,
        widget=forms.CheckboxSelectMultiple,
        label='Parts of speech', 
        choices=list()
    )
    tags = forms.MultipleChoiceField(
        required=False,
        widget=forms.CheckboxSelectMultiple,
        label='Tags', 
        choices=list(),
    )

    def __init__(self, poss=None, tag_list=None, tag_selection=None, *args, **kwargs):
        super(FacetSideBarForm, self).__init__(*args, **kwargs)
        if poss:
            self.fields['poss'].choices = [
                (pos, pos)
                for pos in poss
            ]
        if tag_list:
            self.fields['tags'].choices = [
                (tag, tag)
                for tag in tag_list
            ]

class LemmaFacetForm(FacetSideBarForm):
    initial = forms.ChoiceField(
        widget=forms.HiddenInput(),
        choices=LETTERS,
    )

class SearchFacetForm(FacetSideBarForm):
    search_term = forms.CharField(
        widget=forms.HiddenInput()
    )
    search_type = forms.ChoiceField(
        widget=forms.HiddenInput(),
        choices=SEARCH_OPTIONS,
    )
            

app/emedict/templates/emedict/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<link rel="stylesheet" href="{% static 'emedict/style.css' %}">

<head>
    <title>{% block title %}Emedict: A Sumerian Dictionnary{% endblock %}</title>
</head>

<body>
    <div id="header">
        <h1>Emedict: A Sumerian Dictionnary</h1>
        <ul id="navbar">
            <li><a href="{% url 'emedict:index' %}">Home</a></li>
            <li><a href="{% url 'emedict:lemma_home' %}">Lemmata</a></li>
            <li><a href="{% url 'emedict:tags_home' %}">Tags</a></li>
            <li><a href="{% url 'emedict:comp_verbs' %}">Compound verbs</a></li>
            <li><a href="{% url 'emedict:lemesal' %}">Emesal</a></li>
            <li><a href="{% url 'emedict:txtsource_list' %}">Source texts</a></li>
            <li><a href="">About</a></li>
        </ul>
        <br>
    </div>
    <div id="content">
        {% block content %}{% endblock %}
    </div>
    <div id="footer">
        <hr>
        <p>Emedict v. 0.4.1</p>
    </div>
</body>

</html>

app/emedict/templates/emedict/compverbs.html
{% extends "emedict/base.html" %}
{% block title %}Emedict: compound verbs{% endblock %}
{% block content %}

<div class="floatcont">
    <div class="leftfloat">
        <h2>By component noun</h2>
        <ul>
            {% for lem in nouns %}
            <li>
                <a href="{% url 'emedict:compverbcomp' lem.pk %}">{{ lem.cf }}</a> 
                    ({{ lem.forms.first.spellings.first }}): {{ lem.definitions.first }}
            </li>
            {% endfor %}
        </ul>
    </div>

    <div class="leftfloat">
        <h2>By component verb</h2>
        <ul>
            {% for lem in verbs %}
            <li><a href="{% url 'emedict:compverbcomp' lem.pk %}">{{ lem.cf }}</a> 
                ({{ lem.forms.first.spellings.first }}): {{ lem.definitions.first }}</li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}

app/emedict/templates/emedict/cverbnoun.html
{% extends "emedict/base.html" %}
{% block title %}Emedict: compound verbs{% endblock %}
{% block content %}
<h2>Compound verbs: <a href="{% url 'emedict:lemma' baselem.pk %}">{{ baselem.cf }}</a></h2>
<p>{{ baselem.pos|title }}: {{ baselem.definitions.first }}</p>
<ul>
    {% for lem in lemmalist %}
    <li><a href="{% url 'emedict:lemma' lem.pk %}">{{ lem }}</a>
        {% if baselem.pos.term == "noun" %}
        ({{ lem.forms.first.spellings.first }}):
        {{ lem.definitions.first }}
        <ul>
            {% for comp in lem.components.all %}{% if comp.pos.term == "verb" %}
            <li>
                <a href="{% url 'emedict:lemma' comp.pk %}">{{ comp }}</a>
                ({{ comp.forms.first.spellings.first }}):
                {{ comp.definitions.first }}
            </li>
            {% endif %}
            {% endfor %}
        </ul>
        {% endif %}

        {% if baselem.pos.term == "verb" %}
        ({{ lem.forms.first.spellings.first }}):
        {{ lem.definitions.first }}
        <ul>
            {% for comp in lem.components.all %}{% if comp.pos.term == "noun" %}
            <li>
                <a href="{% url 'emedict:lemma' comp.pk %}">{{ comp }}</a>
                ({{ comp.forms.first.spellings.first }}):
                {{ comp.definitions.first }}
            </li>
            {% endif %}
            {% endfor %}
        </ul>
        {% endif %}
    </li>
    {% endfor %}
</ul>
{% endblock %}

app/emedict/templates/emedict/emedict.html
{% extends "emedict/base.html" %}
{% block title %}Emedict homepage{% endblock %}
{% block content %}
<p>Home text</p>
<ul>
    <li><a href="{% url 'emedict:lemma_home' %}">Lemmata</a></li>
    <li><a href="{% url 'emedict:tags_home' %}">Tags</a></li>
    <li><a href="{% url 'emedict:comp_verbs' %}">Compound verbs</a></li>
</ul>
{% endblock %}

app/emedict/templates/emedict/facet_landing.html
{% extends "emedict/lemma_interface.html" %}
{% block title %}Emedict: facet test{% endblock %}
{% block content %}

    <ul>
    {% for pos in poss %}
    <li>{{ pos }}</li>
    {% endfor %}
    </ul>

    <ul>
        {% for tag in tags %}
        <li>{{ tag }}</li>
        {% endfor %}
    </ul>

    <ul>
        {% for lemma in lemmalist %}
        <li><a href="{% url 'emedict:lemma' lemma.pk %}">{{ lemma.cf }}</a> ({{ lemma.pos }}, {{ lemma.forms.first.spellings.first }}): {{ lemma.definitions.first }}</li>
        {% endfor %}
    </ul>
{% endblock %}

app/emedict/templates/emedict/lemesal.html
{% extends "emedict/base.html" %}
{% block title %}Emedict: lemmata{% endblock %}
{% block content %}

{% if lemmalist %}
<h2>Lemmata with Emesal forms</h2>
<ul>
    {% for lemma in lemmalist %}
    <li><a href="{% url 'emedict:lemma' lemma.pk %}">{{ lemma.emesal_form }}</a> ~ {{ lemma.cf }} ({{lemma.pos}}, {{ lemma.emesal_spelling }}): {{ lemma.definitions.first }}</li>
    {% endfor %}
</ul>
{% else %}
<a href="{% url 'emedict:index' %}">Home</a>
<p>No lemmata are available.</p>
{% endif %}

{% endblock %}

app/emedict/templates/emedict/lemma_home.html
{% extends "emedict/lemma_interface.html" %}
{% block title %}Emedict: lemmata{% endblock %}
{% block lem_main %}
    <ul>
        {% for lemma in lemmalist %}
        <li><a href="{% url 'emedict:lemma' lemma.pk %}">{{ lemma.cf }}</a> ({{ lemma.pos }}, {{ lemma.base_spelling }}): {{ lemma.definitions.first }}</li>
        {% endfor %}
    </ul>
{% endblock %}

app/emedict/templates/emedict/lemma_id.html
{% extends "emedict/base.html" %}

{% block title %}
{% if lemma %}Emedict: {{lemma.cf}}{% endif %}
{% endblock %}

{% block content %}
<form action="{% url 'emedict:lemma_home' %}" method="get">
    {{ lem_init_form }}
    <input type="submit" value="Submit">
</form>
<br>
<form action="{% url 'emedict:lemma_search' %}" method="get">
    {{ lem_search_form }} <input type="submit" value="Submit">
</form>
{% if lemma %}
<h1>{{ lemma.cf|title }}
    {% if lemma.forms.first.spellings.first.spelling_cun %}
    ({{lemma.forms.first.spellings.first.spelling_cun}})
    {% endif %}</h1>

<p>
    <a href="{{ admin_edit }}">Edit</a>
    | <a href="{% url 'emedict:lemma_json' lemma.pk %}">json-ld</a>
    | <a href="{% url 'emedict:lemma_ttl' lemma.pk %}">ttl</a>
</p>
<p>{{ lemma.cf }} ({{ lemma.pos }}):
    {% for oid in lemma.lemmaoid_set.all %}
    <a href="https://oracc.museum.upenn.edu/epsd2/sux/{{oid}}">{{oid}}</a>
    {% endfor %}
</p>

{% if lemma.components.all %}
Components:
{% for comp in lemma.components.all %}
<ul>
    <li><a href="{% url 'emedict:lemma' comp.pk %}">{{comp.cf}}</a> ({{comp.pos}}): {{comp.definitions.first}}</li>
</ul>
{% endfor %}
{% endif %}

<h2>Definitions</h2>
<ul>
    {% for d in lemma.definitions.all %}
    <li>{{ d.definition }}</li>
    {% endfor %}
</ul>

{% if lemma.notes %}
<p>Notes: {{lemma.notes}}</p>
{% endif %}

<div class="floatcont">
    <h2>Forms</h2>
    {% for f in lemma.forms.all %}
    {% if emesal not in f.formtype.all %}
    <div class="leftfloat">
        <p><em>{{ f.cf }}</em>{% if f.formtype.all %} -
            {% for type in f.formtype.all %}{{ type.term }};
            {% endfor %}{% endif %}</p>
        <ul>
            {% for s in f.spellings.all %}
            <li>{{ s.spelling_lat }}{% if s.spelling_cun %}: {{s.spelling_cun}} {% endif %} {% if s.note %} – {{ s.note
                }}{% endif %}</li>
            {% endfor %}
        </ul>
    </div>
    {% endif %}
    {% endfor %}
    {% for f in lemma.forms.all %}
    {% if emesal in f.formtype.all %}
    <div class="leftfloat">
        <p><em>{{ f.cf }}</em>{% if f.formtype.all %} -
            {% for type in f.formtype.all %}{{ type.term }};
            {% endfor %}{% endif %}</p>
        <ul>
            {% for s in f.spellings.all %}
            <li>{{ s.spelling_lat }}{% if s.spelling_cun %}: {{s.spelling_cun}} {% endif %} {% if s.note %} – {{ s.note
                }}{% endif %}</li>
            {% endfor %}
        </ul>
    </div>
    {% endif %}
    {% endfor %}
</div>

{% if lemma.lemmatag_set.all %}
<div>
    <h2>Tags</h2>
    <ul>
        {% for tag in lemma.lemmatag_set.all %}
        <li><a href="{% url 'emedict:tag_id' tag.tag.id %}">{{ tag.tag }}</a> {{ tag.citation }}</li>
        {% endfor %}
    </ul>
</div>
{% endif %}

{% if lemma.lemmacitation_set.all %}
<h2>Citations</h2>

{% for cite in lemma.lemmacitation_set.all %}
<ul>
    <li>{{ cite.citation }}</li>
    {% if cite.gloss %}<li>{{ cite.gloss }}</li>{% endif %}
    {% if cite.trans %}<li>{{ cite.trans }}</li>{% endif %}
    <li>(<a href="{% url 'emedict:txtsource' cite.source.id %}">{{ cite.source.title }}</a>{% if cite.lines %}; {{
        cite.lines }}{% endif %})</li>
</ul>
{% endfor %}
{% endif %}

{% if used_in %}
<h2>Used in</h2>
<ul>
    {% for lem in used_in %}
    <li><a href="{% url 'emedict:lemma' lem.pk %}">{{ lem.cf }}</a>: {{ lem.definitions.first }}</li>
    {% endfor %}
</ul>
{% endif %}

{% else %}
<p>No lemmata are available.</p>
{% endif %}
{% endblock %}

app/emedict/templates/emedict/lemma_interface.html
{% extends "emedict/base.html" %}
{% load emedict_extras %}
{% block title %}Emedict: lemmata{% endblock %}
{% block content %}

<form action="{% url 'emedict:lemma_home' %}" method="get">
    {{ form }}
    <input type="submit" value="Submit">
</form>
<br>
<form action="{% url 'emedict:lemma_search' %}" method="get">
    {{ lem_search_form }} <input type="submit" value="Submit">
</form>
<div class="wrapper" >
    <div class="sidebar">
        <form method="get">
            {{ sidebar_form }}
            <input type="submit" value="Filter">
        </form>
    </div>
    {% if lemmalist %}
    <div class="main">
        {% block lem_main %}{% endblock %}
        <div class="pagination">
            <span class="step-links">
                {% if lemmalist.has_previous %}
                    <a href="?{% url_replace request 'page' 1 %}">&laquo; first</a>
                    <a href="?{% url_replace request 'page' lemmalist.previous_page_number %}">previous</a>
                {% endif %}

                <span class="current">
                    Page {{ lemmalist.number }} of {{ lemmalist.paginator.num_pages }}.
                </span>

                {% if lemmalist.has_next %}
                    <a href="?{% url_replace request 'page' lemmalist.next_page_number %}">next</a>
                    <a href="?{% url_replace request 'page' lemmalist.paginator.num_pages %}">last &raquo;</a>
                {% endif %}
            </span>
        </div>
    </div>
</div>

{% else %}
    <div class="main">
        <ul>
            <p>No lemmata are available.</p>
        </ul>
    </div>
</div>

{% endif %}

{% endblock %}

app/emedict/templates/emedict/lemma_search.html
{% extends "emedict/lemma_interface.html" %}
{% block title %}Emedict: lemma search{% endblock %}
{% block lem_main %}
    <ul>
        {% for lemma in lemmalist %}
        <li><a href="{% url 'emedict:lemma' lemma.pk %}">{{ lemma.cf }}</a> ({{ lemma.pos }}, {{ lemma.base_spelling }}): {{ lemma.definitions.first }}</li>
        {% endfor %}
    </ul>
{% endblock %}

app/emedict/templates/emedict/tags_detail.html
{% extends "emedict/base.html" %}

{% block title %}
    {% if tag %}Emedict: {{ tag.term }}{% endif %}
{% endblock %}

{% block content %}
{% if tag %}
<p><a href="{% url 'emedict:tags_home' %}">Tag categories</a></p>
<h1>{{ tag.term }}</h1>
<p>{{ tag.term }}: {{ tag.definition }}</p>

{% if lemmata %}
<h2>Lemmata</h2>
<ul>
    {% for l in lemmata %}
    <li><a href="{% url 'emedict:lemma' l.pk %}">{{ l.cf }}</a> ({{ l.forms.first.spellings.first.spelling_cun }} {{l.forms.first.spellings.first.spelling_lat}}): {{ l.definitions.first }}</li>
    {% endfor %}
</ul>
{% endif %}

{% else %}
<p>No tag are available.</p>
{% endif %}
{% endblock %}

app/emedict/templates/emedict/txtsource_list.html
{% extends "emedict/base.html" %}
{% block title %}Emedict: Source texts{% endblock %}
{% block content %}

{% if txtlist %}
<h2>Souce texts</h2>
<ul>
    {% for txt in txtlist %}
    <li><a href="{% url 'emedict:txtsource' txt.pk %}">{{ txt.title }}</a></li>
    {% endfor %}
</ul>
{% else %}
<a href="{% url 'emedict:index' %}">Home</a>
<p>No source texts are available.</p>
{% endif %}

{% endblock %}